# Generated by Django 5.2.7 on 2025-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('sample_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='in_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artworkrequest',
            name='status',
            field=models.CharField(choices=[('in_review', 'In review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='in_review', max_length=20),
        ),
    ]
