# Generated by Django 5.2.7 on 2025-10-19 11:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_offer_alter_artworkrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkrequest',
            name='ref_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='artworkrequest',
            name='budget_cents',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
