# Generated by Django 5.2.7 on 2025-10-19 12:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_artworkrequest_ref_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkrequest',
            name='ref_image_url',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sample_image_url',
        ),
        migrations.AddField(
            model_name='offer',
            name='sample_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
