# Generated by Django 5.2.7 on 2025-10-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_artworkrequest_ref_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
