# Generated by Django 5.2.7 on 2025-11-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkrequest',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
