# Generated by Django 5.2.7 on 2025-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('shop', '0003_alter_artwork_options_remove_artwork_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='search_docs', to='shop.category'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='extra_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
