# Generated by Django 5.2.7 on 2025-10-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchdocument_categories_searchdocument_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchdocument',
            name='subtitle',
        ),
    ]
