# Generated by Django 5.2.7 on 2025-10-08 16:32

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
