# Generated by Django 5.2.7 on 2025-10-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_artwork_options_remove_artwork_has_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='created_at',
        ),
    ]
