# Generated by Django 5.2.7 on 2025-10-09 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_artwork_options_remove_artwork_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
