# Generated by Django 5.2.7 on 2025-11-10 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_artwork_options_artwork_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='digital_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='digital'),
        ),
    ]
