# Generated by Django 5.2.7 on 2025-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_artwork_digital_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='digital_file',
        ),
        migrations.AddField(
            model_name='artwork',
            name='digital_file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Download URL'),
        ),
    ]
